exports.templateQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="13.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <TemplateQueryRq></TemplateQueryRq> </QBXMLMsgsRq> </QBXML>`
exports.salesTaxQuery = `<?xml version="1.0" ?><?qbxml version="13.0"><QBXML> <QBXMLMsgsRq onError="stopOnError"><ItemSalesTaxQueryRq requestID="4"></ItemSalesTaxQueryRq>   </QBXMLMsgsRq></QBXML>`;
exports.findCustomerByNameQuery = `<?xml version="1.0" ?><?qbxml version="13.0"><QBXML><QBXMLMsgsRq onError="continueOnError"><CustomerQueryRq requestID="2"><FullName>customerName</FullName></CustomerQueryRq></QBXMLMsgsRq></QBXML>`;
exports.findAllItemQuery = `<?qbxml version="13.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <ItemInventoryQueryRq requestID="1234" /> </QBXMLMsgsRq> </QBXML>`;
exports.findSalesTaxByNameQuery = `<?xml version="1.0" ?><?qbxml version="13.0"><QBXML> <QBXMLMsgsRq onError="stopOnError"><ItemSalesTaxQueryRq requestID="4"><FullName>SALES_TAX_NAME</FullName></ItemSalesTaxQueryRq>   </QBXMLMsgsRq></QBXML>`;
exports.createSalesTaxQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <ItemSalesTaxAddRq> <ItemSalesTaxAdd> <Name >SALES_TAX_NAME</Name> <ItemDesc >SALES_TAX_DESC</ItemDesc> <TaxRate >SALES_TAX_RATE</TaxRate><TaxVendorRef><FullName>SALES_TAX_VENDOR_NAME</FullName></TaxVendorRef> <SalesTaxReturnLineRef><FullName>SALES_TAX_RETURN_LINE</FullName></SalesTaxReturnLineRef> </ItemSalesTaxAdd> </ItemSalesTaxAddRq> </QBXMLMsgsRq> </QBXML>`
exports.subtotalQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <ItemSubtotalQueryRq > <FullName >SUBTOTAL_ITEM_NAME</FullName> </ItemSubtotalQueryRq> </QBXMLMsgsRq> </QBXML>`
exports.createSubtotalItemQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <ItemSubtotalAddRq> <ItemSubtotalAdd> <Name >SUBTOTAL_ITEM_NAME</Name> </ItemSubtotalAdd> </ItemSubtotalAddRq> </QBXMLMsgsRq> </QBXML>`
exports.salesTaxCodeQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <SalesTaxCodeQueryRq > </SalesTaxCodeQueryRq></QBXMLMsgsRq></QBXML>`
exports.createSalesTaxCodeQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <SalesTaxCodeAddRq> <SalesTaxCodeAdd> <Name >SALES_TAX_CODE_NAME</Name> <IsActive >true</IsActive> <IsTaxable >IS_TAXABLE</IsTaxable> <Desc >SALES_TAX_CODE_DESC</Desc> ITEM_SALES_TAX_REF_SNIPPET </SalesTaxCodeAdd> </SalesTaxCodeAddRq></QBXMLMsgsRq></QBXML>`
exports.serviceItemQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <ItemServiceQueryRq> </ItemServiceQueryRq> </QBXMLMsgsRq> </QBXML>`
exports.findAccountsByNameQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <AccountQueryRq> <FullName >ACCOUNT_NAME</FullName> </AccountQueryRq> </QBXMLMsgsRq> </QBXML>`
exports.createAccountQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <AccountAddRq> <AccountAdd> <Name >ACCOUNT_NAME</Name> <AccountType >ACCOUNT_TYPE</AccountType> <Desc ></Desc> </AccountAdd> </AccountAddRq> </QBXMLMsgsRq> </QBXML>`
exports.getInvoiceByRefNumberQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <InvoiceQueryRq> <RefNumber >REF_NUMBER</RefNumber> </InvoiceQueryRq> </QBXMLMsgsRq> </QBXML>`
exports.deleteTransactionQuery = `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"> <TxnDelRq> <TxnDelType >TRANSACTION_TYPE</TxnDelType> <TxnID >TRANSACTION_ID</TxnID> </TxnDelRq> </QBXMLMsgsRq> </QBXML>`
exports.findVendorByNameQuery = `<?xml version="1.0" ?><?qbxml version="13.0"><QBXML><QBXMLMsgsRq onError="continueOnError"><VendorQueryRq requestID="2"><FullName>vendorName</FullName></VendorQueryRq></QBXMLMsgsRq></QBXML>`;
exports.getBillByRefNumberQuery = `<?xml version="1.0" encoding="utf-8"?><?qbxml version="16.0"?><QBXML><QBXMLMsgsRq onError="stopOnError"><BillQueryRq><RefNumber>BILL_REF_NUMBER</RefNumber></BillQueryRq></QBXMLMsgsRq></QBXML>`;
exports.getBillByTxnIdQuery = `<?xml version="1.0" encoding="utf-8"?><?qbxml version="16.0"?><QBXML><QBXMLMsgsRq onError="stopOnError"><BillQueryRq><TxnID>BILL_TXN_ID</TxnID></BillQueryRq></QBXMLMsgsRq></QBXML>`;
exports.discountQuery =  `<?xml version="1.0" encoding="utf-8"?> <?qbxml version="16.0"?> <QBXML> <QBXMLMsgsRq onError="stopOnError"><ItemDiscountQueryRq><FullName>DISCOUNT_ITEM_NAME</FullName></ItemDiscountQueryRq></QBXMLMsgsRq></QBXML>`
